### PR TITLE
sys/stats: Fix build with GCC 9.2.1

### PR DESCRIPTION
**Pull request by andrzej-kaczmarek**
This fixes following build error:

Compiling repos/apache-mynewt-core/sys/stats/full/src/stats.c
Error: In function 'stats_init',
    inlined from 'stats_module_init_internal' at repos/apache-mynewt-core/sys/stats/full/src/stats.c:148:10:
repos/apache-mynewt-core/sys/stats/full/src/stats.c:298:5: error: 'memset' offset [13, 16] from the object
at 'g_stats_stats' is out of the bounds of referenced subobject 's_hdr' with type 'struct stats_hdr'
at offset 0 [-Werror=array-bounds]
  298 |     memset((uint8_t *)shdr + offset, 0, size * cnt);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

I do not really like that we have separate macros for retrieving const
and non-const data pointer, but I do not see any easy way to workaround
this except for removing consts explicitly which basically original
private API did by casting to uint8_t*.

### CODE REVIEW

**Comment by andrzej-kaczmarek** [comment]
Perhaps someone has some better idea how to fix this... :)

File: sys/stats/full/include/stats/stats.h [hunk 1]
```diff
@@ -48,6 +48,7 @@ struct stats_hdr {
     int s_map_cnt;
 #endif
     STAILQ_ENTRY(stats_hdr) s_next;
+    uint8_t data[0];
```
Comment (ccollins476ad) [inline sys/stats/full/include/stats/stats.h:51]: The C standard prohibits zero-length arrays (gcc allows them as an extension).  The pedantically correct way to do this is to use a "flexible array member", i.e.,
```
uint8_t data[]
```

File: sys/stats/full/src/stats.c [hunk 2]
```diff
@@ -96,13 +92,24 @@ stats_size(const struct stats_hdr *hdr)
...
-    offset = stats_offset(hdr);
-    return (uint8_t *)hdr + offset;
+void *
+stats_data_rw(struct stats_hdr *hdr)
+{
+    if (hdr->s_flags & STATS_HDR_F_PERSIST) {
+        return &((struct stats_persisted_hdr *)hdr)->data[0];
+    } else {
+        return &hdr->data[0];
+    }
```
Comment (ccollins476ad) [inline sys/stats/full/src/stats.c:112]: You might consider implementing this in terms of `stats_data_ro`.  If the stats object is not actually const (i.e., not actually located in read-only memory), then it is safe to cast away const from the result of `stats_data_ro` and return that.

I don't feel strongly about this at all.  Just throwing it out there.
